on: [push]

jobs:
  golox_test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: ./.github/actions
        id: glox_test
