on: [push]

jobs:
  golox_test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker test image
        run: docker build -t local < .devcontainer/Dockerfile
      - name: Run test suite
        run: docker run -it local
